/* tslint:disable */
/* eslint-disable */
/**
 * Mini Ats Tracker API
 * A simple API for managing applicants and job postings
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApplicantRequest
 */
export interface ApplicantRequest {
    /**
     * 
     * @type {string}
     * @memberof ApplicantRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApplicantRequest
     */
    'email': string;
}

