/* tslint:disable */
/* eslint-disable */
/**
 * Mini Ats Tracker API
 * A simple API for managing applicants and job postings
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Applicant
 */
export interface Applicant {
    /**
     * 
     * @type {number}
     * @memberof Applicant
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Applicant
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Applicant
     */
    'email': string;
}

