/* tslint:disable */
/* eslint-disable */
/**
 * Mini Ats Tracker API
 * A simple API for managing applicants and job postings
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Applicant } from './applicant';
// May contain unused imports in some cases
// @ts-ignore
import type { JobPosting } from './job-posting';
// May contain unused imports in some cases
// @ts-ignore
import type { StatusEnum } from './status-enum';

/**
 * 
 * @export
 * @interface Application
 */
export interface Application {
    /**
     * 
     * @type {number}
     * @memberof Application
     */
    'id': number;
    /**
     * 
     * @type {Applicant}
     * @memberof Application
     */
    'applicant': Applicant;
    /**
     * 
     * @type {JobPosting}
     * @memberof Application
     */
    'job': JobPosting;
    /**
     * 
     * @type {StatusEnum}
     * @memberof Application
     */
    'status'?: StatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Application
     */
    'notes': string;
    /**
     * 
     * @type {string}
     * @memberof Application
     */
    'applied_at': string;
}



