/* tslint:disable */
/* eslint-disable */
/**
 * Mini Ats Tracker API
 * A simple API for managing applicants and job postings
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LocationEnum } from './location-enum';

/**
 * 
 * @export
 * @interface JobPosting
 */
export interface JobPosting {
    /**
     * 
     * @type {number}
     * @memberof JobPosting
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof JobPosting
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof JobPosting
     */
    'description': string;
    /**
     * 
     * @type {LocationEnum}
     * @memberof JobPosting
     */
    'location'?: LocationEnum;
    /**
     * 
     * @type {number}
     * @memberof JobPosting
     */
    'created_by': number;
    /**
     * 
     * @type {string}
     * @memberof JobPosting
     */
    'created_at': string;
}



