/* tslint:disable */
/* eslint-disable */
/**
 * Mini Ats Tracker API
 * A simple API for managing applicants and job postings
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LocationEnum } from './location-enum';

/**
 * 
 * @export
 * @interface JobPostingRequest
 */
export interface JobPostingRequest {
    /**
     * 
     * @type {string}
     * @memberof JobPostingRequest
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof JobPostingRequest
     */
    'description': string;
    /**
     * 
     * @type {LocationEnum}
     * @memberof JobPostingRequest
     */
    'location'?: LocationEnum;
}



