/* tslint:disable */
/* eslint-disable */
/**
 * Mini Ats Tracker API
 * A simple API for managing applicants and job postings
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * * `remote` - Remote * `on_site` - On Site * `hybrid` - Hybrid
 * @export
 * @enum {string}
 */

export const LocationEnum = {
    Remote: 'remote',
    OnSite: 'on_site',
    Hybrid: 'hybrid'
} as const;

export type LocationEnum = typeof LocationEnum[keyof typeof LocationEnum];



