/* tslint:disable */
/* eslint-disable */
/**
 * Mini Ats Tracker API
 * A simple API for managing applicants and job postings
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StatusEnum } from './status-enum';

/**
 * 
 * @export
 * @interface PatchedApplicationRequest
 */
export interface PatchedApplicationRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedApplicationRequest
     */
    'applicant_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedApplicationRequest
     */
    'job_id'?: number;
    /**
     * 
     * @type {StatusEnum}
     * @memberof PatchedApplicationRequest
     */
    'status'?: StatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedApplicationRequest
     */
    'notes'?: string;
}



