/* tslint:disable */
/* eslint-disable */
/**
 * Mini Ats Tracker API
 * A simple API for managing applicants and job postings
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * * `applied` - Applied * `interviewing` - Interviewing * `hired` - Hired * `rejected` - Rejected
 * @export
 * @enum {string}
 */

export const StatusEnum = {
    Applied: 'applied',
    Interviewing: 'interviewing',
    Hired: 'hired',
    Rejected: 'rejected'
} as const;

export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];



